<?php
/**
 * @author markus
 */
$this->headLink()->appendStylesheet('/css/mail.css');
?>
	<h1><?php print I18n::_('View own Mail'); ?></h1>
<?php
if (count($this->headers) == 0) {
	print I18n::_('You currently have no mail.');
} else { ?>
	<table>
	<tr>
		<th class="col1"><?php print I18n::_('From'); ?></th>
		<th class="col2"><?php print I18n::_('To'); ?></th>
		<th class="col3"><?php print I18n::_('Subject'); ?></th>
		<th class="col4"><?php print I18n::_('Date'); ?></th>
		<th class="col5"><?php print I18n::_('Size'); ?></th>
		<th class="col6"><?php print I18n::_('Del'); ?></th>
	</tr>
	<?php
	foreach ($this->headers as $header) {
		?>
		<tr>
			<td><a href="<?= $header->detailslink ?>"><?= $header->fromaddress ?></a></td>
			<td><?= $header->toaddress ?></td>
			<td><?= htmlspecialchars(iconv_mime_decode($header->subject, ICONV_MIME_DECODE_CONTINUE_ON_ERROR, 'UTF-8'),
					ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?></td>
			<td><?= $header->MailDate ?></td>
			<td><?= $header->Size ?></td>
			<td><a class="delete" href="<?= $header->deletelink ?>"><img src="/img/delete_icon.jpg"></a></td>
		</tr>
		<?php
	} ?>
	</table><?php
}